### ISSUE TITLE
Add Jcord

### ISSUE THREAD

**Issue by KevvyCodes** [boltxyz/awesome-discord#2]
### Main programming language

Javascript

### Submission's Title

JCord

### Submission's URL

https://github.com/KevvyCodes/JCord

### Submission's Category
* [x] Libraries
* [ ] Frameworks
* [ ] Guides
* [ ] Miscellaneous

**Comment by boltxyz** [comment]
Hey @KevvyCodes,
Thanks for the submission!
We've added JCord in the list.
